services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: notes-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/notesdb

  test-runner:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: notes-api-test-runner
    depends_on:
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    command: mvn test
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/notesdb

volumes:
  mongo_data: